import { CardConfig } from "@/features/types/landing.types";
import { FloatingShapeConfig } from "@/shared/types/ui";
import { Target, Users, Award, UserPlus, Lock, Trophy } from "lucide-react";

export const cards: CardConfig[] = [
  {
    icon: Target,
    translationKey: "pickScores",
    borderColor: "border-wc-red/30 dark:border-zinc-800 hover:border-wc-red dark:hover:border-wc-red",
    gradientFrom: "from-wc-red/50 to-wc-red",
    gradientTo: "dark:from-wc-red/20 dark:via-wc-orange/30 dark:to-wc-purple/50",
    gradientDark: "",
    delay: 0,
  },
  {
    icon: Award,
    translationKey: "earnPoints",
    borderColor: "border-wc-orange/30 dark:border-zinc-800 hover:border-wc-orange dark:hover:border-wc-orange",
    gradientFrom: "from-wc-orange/50 to-wc-orange",
    gradientTo: "dark:from-wc-orange/20 dark:via-wc-purple/30 dark:to-wc-red/50",
    gradientDark: "",
    delay: 150,
  },
  {
    icon: Users,
    translationKey: "compete",
    borderColor: "border-wc-purple/30 dark:border-zinc-800 hover:border-wc-purple dark:hover:border-wc-purple",
    gradientFrom: "from-wc-purple/50 to-wc-purple",
    gradientTo: "dark:from-wc-purple/20 dark:via-wc-red/30 dark:to-wc-orange/50",
    gradientDark: "",
    delay: 300,
  },
  {
    icon: UserPlus,
    translationKey: "joinLeague",
    borderColor: "border-wc-red/30 dark:border-zinc-800 hover:border-wc-red dark:hover:border-wc-red",
    gradientFrom: "from-wc-red/50 to-wc-red",
    gradientTo: "dark:from-wc-red/20 dark:via-wc-orange/30 dark:to-wc-purple/50",
    gradientDark: "",
    delay: 450,
  },
  {
    icon: Lock,
    translationKey: "matchLock",
    borderColor: "border-wc-orange/30 dark:border-zinc-800 hover:border-wc-orange dark:hover:border-wc-orange",
    gradientFrom: "from-wc-orange/50 to-wc-orange",
    gradientTo: "dark:from-wc-orange/20 dark:via-wc-purple/30 dark:to-wc-red/50",
    gradientDark: "",
    delay: 600,
  },
  {
    icon: Trophy,
    translationKey: "masterTheBracket",
    borderColor: "border-wc-purple/30 dark:border-zinc-800 hover:border-wc-purple dark:hover:border-wc-purple",
    gradientFrom: "from-wc-purple/50 to-wc-purple",
    gradientTo: "dark:from-wc-purple/20 dark:via-wc-red/30 dark:to-wc-orange/50",
    gradientDark: "",
    delay: 750,
  },
];

export const floatingShapes: FloatingShapeConfig[] = [
  {
    color: "purple",
    shape: "square",
    size: 80,
    opacity: 70,
    darkOpacity: 30,
    blur: "none",
    position: { top: "10%", right: "5%" },
    rotation: 12,
    animation: "rotate",
    animationDuration: 15,
  },
  { color: "purple", size: 64, opacity: 70, darkOpacity: 30, blur: "none", position: { bottom: "15%", left: "25%" }, animation: "bounce", animationDelay: 0.5 },
  {
    color: "orange",
    shape: "diamond",
    size: 48,
    opacity: 70,
    darkOpacity: 30,
    blur: "none",
    position: { top: "50%", right: "25%" },
    animation: "zigzag",
    animationDelay: 1,
  },
  {
    color: "red",
    shape: "diamond",
    size: 56,
    opacity: 70,
    darkOpacity: 30,
    blur: "none",
    position: { bottom: "33%", left: "33%" },
    animation: "wave",
    animationDelay: 2,
  },
  { color: "orange", size: 72, opacity: 60, darkOpacity: 25, blur: "none", position: { top: "20%", left: "10%" }, animation: "float", animationDelay: 0.3 },
  {
    color: "red",
    shape: "square",
    size: 64,
    opacity: 65,
    darkOpacity: 28,
    blur: "none",
    position: { bottom: "20%", right: "8%" },
    rotation: 25,
    animation: "drift",
    animationDelay: 1.8,
  },
  {
    color: "purple",
    shape: "diamond",
    size: 52,
    opacity: 55,
    darkOpacity: 22,
    blur: "none",
    position: { top: "70%", left: "15%" },
    animation: "pulse",
    animationDelay: 2.5,
  },
];
